apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webapp-deployment
  labels:
    app: go-webapp
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: go-webapp-container
          image: thedevfactor/go-webapp:a2f61e62243bcf5f1164922507a20071704e8bc7