apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webapp-deployment
  labels:
    app: go-webapp
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: go-webapp-container
          image: thedevfactor/go-webapp:image-tag