resources:
  - ../../base
  - namespace.yaml

namespace: production

patches:
  - patch: patches/go-deployment-patch.yaml

configMapGenerator:
  - name: go-envs
    envs:
      - envs/go.env.example

secretGenerator:
  - name: go-secrets
    files:
      - secrets/news_api_key.secret.example