apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-news-webapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/FaisalAl-Rayes/go-k8-argocd.git
    targetRevision: HEAD
    path: gitops_kubernetes_manifests/overlays/development

  destination:
    server: https://kubernetes.default.svc
    namespace: development

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
