# git commit: 8329663876e1f6f9104068a9f265a2e5198f9974
apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
data:
  PORT: "8080"
kind: ConfigMap
metadata:
  name: go-envs-td2thftdb5
  namespace: development
---
apiVersion: v1
data:
  NEWS_API_KEY: ZGVtbyBrZXkgc2hvdWxkIGJlIGhlcmUgYnV0IG5pY2UgdHJ5
kind: Secret
metadata:
  name: go-secrets-7tcf4hmdd7
  namespace: development
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: go-webapp-service
  namespace: development
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-webapp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-webapp
  name: go-webapp-deployment
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-webapp
  template:
    metadata:
      labels:
        app: go-webapp
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: go-secrets-7tcf4hmdd7
        - configMapRef:
            name: go-envs-td2thftdb5
        image: localhost:5000/go-webapp-image:latest
        name: go-webapp-container
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.2"
            memory: 256Mi
