# git commit: 8b7bff5c7cf1c53b272cdcfae37e9b66b6056db4
apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
data:
  PORT: "8080"
kind: ConfigMap
metadata:
  name: go-envs-td2thftdb5
  namespace: development
---
apiVersion: v1
data:
  news_api_key.secret: TkVXU19BUElfS0VZPWRlbW8ga2V5IHNob3VsZCBiZSBoZXJlIGJ1dCBuaWNlIHRyeQo=
kind: Secret
metadata:
  name: go-secrets-tfkd2thhb4
  namespace: development
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: go-webapp-service
  namespace: development
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-webapp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-webapp
  name: go-webapp-deployment
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-webapp
  template:
    metadata:
      labels:
        app: go-webapp
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: go-envs-td2thftdb5
        image: localhost:5000/go-webapp-image:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        name: go-webapp-container
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.2"
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - NET_RAW
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /secrets
          name: news-api-key
      volumes:
      - name: news-api-key
        secret:
          secretName: go-secrets-tfkd2thhb4
