resources:
  - ../../base
  - namespace.yaml

namespace: development

patches:
  - path: patches/go-deployment-patch.yaml

configMapGenerator:
  - name: go-envs
    envs:
      - envs/go.env

secretGenerator:
  - name: go-secrets
    files:
      - secrets/news_api_key.secret